### ISSUE TITLE
don't emit files with no fuzz functions

### ISSUE THREAD

**Issue by josharian** [thepudds/fzgen#5]
fzgen generated this:

```go
package nettype

// if needed, fill in imports or run 'goimports'
```

May as well not. :)

**Comment by thepudds** [comment]
Agreed, not useful 👍

**Comment by thepudds** [comment]
Hi @josharian, FYI, #15 hopefully fixes this.

### Additional details, if interested 

If I do the following using latest fzgen commit 8b69400 with `go1.17.3 linux/amd64`:

Setup:
```
git clone https://github.com/tailscale/tailscale tailscale
cd tailscale
go install github.com/thepudds/fzgen/cmd/fzgen@8b69400
go get github.com/thepudds/fzgen/fuzzer@8b69400
go mod tidy
```

And then do the following from tailscale repo root:
```
fzgen ./...
cat types/nettype/autofuzz_test.go
```

I get:
```go
func Fuzz_Std_ListenPacket(f *testing.F) {
        f.Fuzz(func(t *testing.T, data []byte) {
                var _x1 Std
                var ctx context.Context
                var network string
                var address string
                fz := fuzzer.NewFuzzer(data)
                fz.Fill(&_x1, &ctx, &network, &address)

                _x1.ListenPacket(ctx, network, address)
        })
}
```

Not the most exciting fuzz function, but there it is.

At this point, fzgen does not generate any autofuzz_test.go files without any funcs in the tailscale repo:

```
$ find . -name "autofuzz_test.go" -exec egrep -L "^W*func" {} \; | wc -l
0
```

When you tried it and reported this issue, fzgen was not properly handing the omitted receiver name in ListenPacket in that nettype package:
```go
func (Std) ListenPacket(ctx context.Context, network, address string) (net.PacketConn, error) {
```

Thanks again for the report!
